In [1]:
import numpy as np

Creating a Matrix using numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])

In [3]:
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [6]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [10]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.04180661 0.53304339 0.52048352]
 [0.93588535 0.86565703 0.95943258]
 [0.88785552 0.77866418 0.11646765]]


In [11]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[80 74 75  3  5]
 [61 64 36 65 68]
 [75 77 85 74 86]
 [ 9 38 53 21 61]]


Matrix with all the values as 1

In [14]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
matrix_3 = np.ones((2,3), dtype = int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [16]:
matrix_3 = np.ones((10,10), dtype = int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [18]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [20]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [23]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[41 92 44  5 39]
 [28 32  0 83 34]
 [61  9 33 57 71]
 [59 89 67 78 61]]


In [25]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[41 28 61 59]
 [92 32  9 89]
 [44  0 33 67]
 [ 5 83 57 78]
 [39 34 71 61]]
