Importing Numpy Library

In [1]:
import numpy as np

# Matrix Addition

Two Matrices can be added only if they have the same shpe

In [2]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:
print(B)

[[6 7]
 [8 9]]


In [5]:
A.shape

(2, 2)

In [6]:
B.shape

(2, 2)

Adding two Matrices

In [7]:
sum = A + B

In [8]:
print(sum)

[[ 8 10]
 [12 14]]


In [10]:
# create two metrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [11]:
print(matrix_1)

[[8 2 0]
 [1 8 2]
 [6 5 3]]


In [12]:
print(matrix_2)

[[ 1 18 12]
 [10  1  1]
 [17 12  3]]


In [13]:
sum = np.add(matrix_1,matrix_2)

In [14]:
print(sum)

[[ 9 20 12]
 [11  9  3]
 [23 17  6]]


In [17]:
# create two metrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [18]:
sum_2 = np.add(matrix_3,matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because shape of matrix_3 and matrix_4 are different

Matrix Subtraction

In [19]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [21]:
print(A)

[[2 3]
 [4 5]]


In [22]:
print(B)

[[6 7]
 [8 9]]


In [20]:
difference = A - B

In [23]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [24]:
# create two metrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [25]:
print(matrix_1)

[[0 0 6]
 [2 9 6]
 [3 9 4]]


In [26]:
print(matrix_2)

[[19 12 12]
 [15 13  7]
 [ 7  8  9]]


In [27]:
diff = np.subtract(matrix_1, matrix_2)

In [28]:
print(diff)

[[-19 -12  -6]
 [-13  -4  -1]
 [ -4   1  -5]]


Multiplying a matrix by a scaler

In [30]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[9 5 7 0]
 [5 5 6 6]
 [8 5 3 2]
 [7 5 4 0]]


In [31]:
product = np.multiply(x,y)

In [32]:
print(product)

[[45 25 35  0]
 [25 25 30 30]
 [40 25 15 10]
 [35 25 20  0]]


# Multiplying 2 Matrices

In [33]:
# create two metrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [34]:
print(matrix_3)

[[1 4 1]
 [1 2 0]
 [3 2 1]]


In [35]:
print(matrix_4)

[[4 0 2 3]
 [2 3 2 0]
 [1 3 4 1]]


In [37]:
product = np.dot(matrix_3,matrix_4)

In [38]:
print(product)

[[13 15 14  4]
 [ 8  6  6  3]
 [17  9 14 10]]


In [46]:
product.shape

(3, 4)

In [40]:
# create two metrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [41]:
product = np.dot(matrix_3,matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

# Elements wise Matrix Multiplication

In [47]:
# create two metrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [48]:
print(matrix_3)

[[2 4 2]
 [2 0 0]
 [4 1 4]]


In [49]:
print(matrix_4)

[[1 4 4]
 [1 2 2]
 [3 0 2]]


In [50]:
product = np.multiply(matrix_3,matrix_4)

In [51]:
print(product)

[[ 2 16  8]
 [ 2  0  0]
 [12  0  8]]


In [56]:
# create two metrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [57]:
product = np.multiply(matrix_3,matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 